services:
  cloudflared:
    image: visibilityspots/cloudflared
    container_name: cloudflared
    hostname: cloudflared
    ports:
      - "5053:5053/tcp"
      - "5053:5053/udp"
    environment:
      - UPSTREAM1=https://dns.quad9.net/dns-query
      - UPSTREAM2=https://cloudflare-dns.com/dns-query
      - TZ=Asia/Jakarta
      - PORT=5053
      - ADDRESS=0.0.0.0
    restart: unless-stopped
    networks:
      pihole-cloudflared-networks:
        ipv4_address: 10.0.0.2

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8080:80/tcp"
      - "8443:443/tcp"
    environment:
      - TZ=Asia/Jakarta
      - FTLCONF_dns_upstreams=10.0.0.2#5053
      - FTLCONF_webserver_api_password=${WEB_SRV_PASSWD}
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    depends_on:
      - cloudflared
    restart: unless-stopped
    networks:
      - pihole-cloudflared-networks

networks:
  pihole-cloudflared-networks:
    ipam:
      config:
        - subnet: 10.0.0.0/29
